#!/usr/bin/env python3
"""Re-inline the modular showcase source into the served dashboard templates.

Two dashboards are built from this one source directory:

  * ``NERVE Dashboard.html`` (scripted demo)  → ``templates/index.html``  (served at ``/``)
  * ``live.html`` (real-backend adapter)       → ``templates/live.html``   (served at ``/live``)

Both reuse the same components and ``styles.css``; they differ only in their
data layer (``data.jsx`` vs ``live-data.jsx`` + ``app.jsx`` vs ``live-app.jsx``).
Edit the modular ``*.jsx`` / ``styles.css`` here, then run:

    python dashboard/showcase_src/build.py

The legacy vanilla dashboard lives at ``templates/live-classic.html`` (served at
``/live-classic``) and is not generated by this script.
"""

from __future__ import annotations

import re
from pathlib import Path

SRC = Path(__file__).resolve().parent
TPL = SRC.parent / "templates"

# (shell file in SRC, output file in TPL, one-line provenance note)
BUILDS = [
    ("NERVE Dashboard.html", "index.html",
     "scripted showcase — edit dashboard/showcase_src, regenerate with build.py. /live is the real-data version."),
    ("live.html", "live.html",
     "real-backend live dashboard — edit dashboard/showcase_src, regenerate with build.py. / is the scripted showcase."),
]


def _inline(shell_text: str) -> str:
    """Inline styles.css and every text/babel script referenced by a shell."""
    styles = (SRC / "styles.css").read_text()
    out = shell_text.replace(
        '<link rel="stylesheet" href="styles.css" />',
        f"<style>\n{styles}\n</style>",
    )

    def repl(match: re.Match[str]) -> str:
        fname = match.group(1)
        content = (SRC / fname).read_text()
        return f'<script type="text/babel" data-source="{fname}">\n{content}\n</script>'

    return re.sub(r'<script type="text/babel" src="([^"]+)"></script>', repl, out)


def build() -> None:
    """Assemble both served dashboards from the modular source."""
    for shell_name, out_name, note in BUILDS:
        shell = (SRC / shell_name).read_text()
        html = _inline(shell)
        html = html.replace("<!DOCTYPE html>", f"<!DOCTYPE html>\n<!-- NERVE — {note} -->")
        out = TPL / out_name
        out.write_text(html)
        print(f"wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    build()
